// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHeM-c9PweEB1AVZWHMuWmzMaEnmPhdJs',
    appId: '1:299857184795:web:00686e717f3871ee6a50be',
    messagingSenderId: '299857184795',
    projectId: 'invisible-garage',
    authDomain: 'invisible-garage.firebaseapp.com',
    storageBucket: 'invisible-garage.appspot.com',
    measurementId: 'G-CGS66EG6NM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDteJZ9QN2xeMgf9DtTvOc04RiaopsAjSQ',
    appId: '1:299857184795:android:ec25020da0ecfcb46a50be',
    messagingSenderId: '299857184795',
    projectId: 'invisible-garage',
    storageBucket: 'invisible-garage.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgMx2qb7qVNJkzyTD4eTvdWrZWbPA7tMA',
    appId: '1:299857184795:ios:d76762d046b44d416a50be',
    messagingSenderId: '299857184795',
    projectId: 'invisible-garage',
    storageBucket: 'invisible-garage.appspot.com',
    iosBundleId: 'com.example.my1st',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgMx2qb7qVNJkzyTD4eTvdWrZWbPA7tMA',
    appId: '1:299857184795:ios:e1d56c8099e8b01c6a50be',
    messagingSenderId: '299857184795',
    projectId: 'invisible-garage',
    storageBucket: 'invisible-garage.appspot.com',
    iosBundleId: 'com.example.my1st.RunnerTests',
  );
}
